REM BAT QUE CREA VARIABLES DE ENTORNO MODIFICAR SEGUN SEA NECESARIO.
REM EL .BAT SE TIENE QUE EJECUTAR COMO ADMINISTRADOR.

@echo off
setx RIEMON_SERVER_SQL /m "127.0.0.1"
setx RIEMON_PORT_SQL /m "3306"
setx RIEMON_USER_SQL /m "root"
setx RIEMON_PASS_SQL /m "L3nt3j4"
setx RIEMON_DB_SQL /m "riemon"
setx RIEMON_DB_VAL1 /m "papa"
setx RIEMON_DB_VAL2 /m "frita"
setx RIEMON_DB_VAL3 /m "rica"
pause